# Generated by Django 5.0 on 2023-12-28 19:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_alter_activity_name_alter_activity_slug_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trail',
            name='route_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.routetype'),
        ),
    ]
