# Generated by Django 5.0 on 2024-01-01 12:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trails', '0002_alter_trail_avg_rating_alter_trail_popularity'),
    ]

    operations = [
        migrations.AddField(
            model_name='trail',
            name='featured_image',
            field=models.ImageField(blank=True, default='default.webp', null=True, upload_to=''),
        ),
    ]
