# Generated by Django 5.0 on 2024-01-01 16:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trails', '0003_trail_featured_image'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='trail',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='users.profile'),
        ),
    ]
