# Generated by Django 5.0 on 2024-01-01 17:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('trails', '0004_trail_created_by'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='trail',
            name='created_by',
        ),
    ]
