# Generated by Django 5.0 on 2024-01-03 03:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trails', '0006_alter_trail_options_alter_review_unique_together'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='trail',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='trails.trail'),
        ),
    ]
