# Generated by Django 5.0 on 2024-01-01 17:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trails', '0005_remove_trail_created_by'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='fvrt_activities',
            field=models.ManyToManyField(blank=True, to='trails.activity'),
        ),
    ]
