# Generated by Django 5.0 on 2024-01-01 21:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_profile_fvrt_activities'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='social_github',
            new_name='social_facebook',
        ),
        migrations.RenameField(
            model_name='profile',
            old_name='social_linkedin',
            new_name='social_instagram',
        ),
    ]
